# Generated by Django 5.2.3 on 2025-06-24 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qotd', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='quote',
            name='approved',
            field=models.BooleanField(default=False),
        ),
    ]
